---

- hosts: all
  #user: ansadmin
  become_method: sudo
  tasks:
    - name: 1. Install latest version of apache
      #yum: check-update    
      yum: name=apache2 state=latest
      become: true
    - name: 2. start apache
      service: name=apache2 state=started enabled=yes
      become: true
    - name: 3. copy standart index.html
      copy: src=/tmp/index.html dest=/var/www/html/index.html mode=0664
      become: true
    - name: 4. save iptables
      command: iptables-save
      become: true
